server:
  port: 8010

eureka:
  client:
    service-url:
      #集群指向其它eureka
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: provider
